---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/build-bun-cli.yml@fcc6d0528cf0533614d1162c5c5b8ebbb6dfdad5 # 20261008.1
    with:
      smoke-test: ./dist/music-assistant-tui --help
