---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    # master
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/lint-oxlint.yml@f72d1eb6c310502499f5551d65ceca1e478eb266 # 20261003.0
  ci:
    # yamllint disable-line rule:line-length
    uses: timmo001/workflows/.github/workflows/build-bun-cli.yml@f72d1eb6c310502499f5551d65ceca1e478eb266 # 20261003.0
    with:
      smoke-test: ./dist/music-assistant-tui --help
