---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@7ac3ee6a5cacd7990795d77fea2f90a9848e5726 # master
    permissions:
      pull-requests: write
      contents: write
